WIP: minimal failing model
vivarium.framework.population.PopulationError: The columns {'age', 'sex'} are required, but are not created by any components in the system.